name: Deploy to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: secret
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install

      - name: Build
        run: bin/bridgetown deploy

      - name: Push
        run: |
              cd output
              git config --global user.email "evsvmx@gmail.com"
              git config --global user.name "Evseev Maxim"
              git init --initial-branch=output
              touch ./.nojekyll
              git add -A
              git commit -m 'deploy'
              git push -f https://q6q9:${{ secrets.SECRET_KEY }}@github.com/q6q9/course_builder_bt.git output
